### ISSUE TITLE
Save and Switch Multiple Instances

### ISSUE THREAD

**Issue by Sconioo** [dark-eye/udiaspora#5]
Hello, it would be interesting to be able to save multiple instances and switch through your menu, which is very well thought out :)

**Comment by dark-eye** [comment]
Hmm you mean to add multiple contexts  that you can switch between them?
good idea! We can also associate to a diaspora pod  so each context can use a different site.

**Comment by dark-eye** [comment]
I`'ve added profile support to the app if you would like to test it before delivery to open store, you can get it [here](https://pookies.owncube.cloud/index.php/s/2ymsr5wwmg5ig7o)

Thanks for suggesting this improvement :)
